### ISSUE TITLE
List of buttons

### ISSUE THREAD

**Issue by nallias** [tinymce/tinymce-docs-4x#13]
Hi,
I am looking for the list (and the documentation) related to the buttons. [Such a list exists for v3](https://www.tiny.cloud/docs-3x/reference/buttons/), but what about v4?
Thanks by advance.

**Comment by tylerkelly13** [comment]
@nallias this list can be found here: https://www.tiny.cloud/docs-4x/advanced/editor-control-identifiers/ for TinyMCE 4 and https://www.tiny.cloud/docs/advanced/editor-control-identifiers/ for TinyMCE 5.
